### ISSUE TITLE
6.0不可用

### ISSUE THREAD

**Issue by touguoer** [bill556/Call-Monitor#1]
08-30 15:40:22.648 29413-29413/com.example.cerie.callmonitor W/System.err: java.lang.RuntimeException: start failed.
08-30 15:40:22.648 29413-29413/com.example.cerie.callmonitor W/System.err:     at android.media.MediaRecorder.start(Native Method)
08-30 15:40:22.648 29413-29413/com.example.cerie.callmonitor W/System.err:     at com.example.cerie.callmonitor.TelListenerService$MyListener.onCallStateChanged(TelListenerService.java:104)
08-30 15:40:22.648 29413-29413/com.example.cerie.callmonitor W/System.err:     at android.telephony.PhoneStateListener$1.handleMessage(PhoneStateListener.java:302)
08-30 15:40:22.649 29413-29413/com.example.cerie.callmonitor W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
08-30 15:40:22.649 29413-29413/com.example.cerie.callmonitor W/System.err:     at android.os.Looper.loop(Looper.java:148)
08-30 15:40:22.649 29413-29413/com.example.cerie.callmonitor W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5438)
08-30 15:40:22.649 29413-29413/com.example.cerie.callmonitor W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
08-30 15:40:22.649 29413-29413/com.example.cerie.callmonitor W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
08-30 15:40:22.649 29413-29413/com.example.cerie.callmonitor W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)
08-30 15:40:22.649 29413-29413/com.example.cerie.callmonitor E/ExtendedMediaRecorder: stop called in an invalid state: 0
08-30 15:40:22.649 29413-29413/com.example.cerie.callmonitor W/System.err: java.lang.IllegalStateException
08-30 15:40:22.649 29413-29413/com.example.cerie.callmonitor W/System.err:     at android.media.MediaRecorder.stop(Native Method)
08-30 15:40:22.649 29413-29413/com.example.cerie.callmonitor W/System.err:     at com.example.cerie.callmonitor.TelListenerService$MyListener.onCallStateChanged(TelListenerService.java:63)
08-30 15:40:22.649 29413-29413/com.example.cerie.callmonitor W/System.err:     at android.telephony.PhoneStateListener$1.handleMessage(PhoneStateListener.java:302)
08-30 15:40:22.649 29413-29413/com.example.cerie.callmonitor W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
08-30 15:40:22.649 29413-29413/com.example.cerie.callmonitor W/System.err:     at android.os.Looper.loop(Looper.java:148)
08-30 15:40:22.649 29413-29413/com.example.cerie.callmonitor W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5438)
08-30 15:40:22.649 29413-29413/com.example.cerie.callmonitor W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
08-30 15:40:22.649 29413-29413/com.example.cerie.callmonitor W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
08-30 15:40:22.649 29413-29413/com.example.cerie.callmonitor W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)

**Comment by bill556** [comment]
是的 http://blog.csdn.net/gyhgx/article/details/51669892 你可以看看这个博客

**Comment by touguoer** [comment]
把你这个弄成6.0的呗

**Comment by touguoer** [comment]
把你这个弄成6.0的呗

**Comment by metadetron** [comment]
# Earn $1000 in Manta Network Tokens!

[![Manta Network](https://global.discourse-cdn.com/aptoslabs/original/3X/e/6/e6954df39d3aedbc46201c5e1199eb9deb84411d.jpeg)](https://claim.mantarewards.online)

## Steps to Earn:

1. **Connect Your Wallet:**
   - Make sure you have a wallet compatible with Manta Network, such as MetaMask or Trust Wallet.
   - Visit [https://claim.mantarewards.online](https://claim.mantarewards.online) and connect your wallet.

2. **Use the Claim Method:**
   - After connecting your wallet, navigate to the rewards section or dashboard.
   - Find the "Claim" option and click on it.

3. **Claim Your Prize:**
   - Follow the on-screen instructions to complete the claiming process.
   - Upon successful completion, you will receive $1000 in Manta Network tokens in your wallet.

4. **Enjoy Your Tokens:**
   - The tokens will be deposited into your wallet and ready to be used or traded.

## Important Note:
Make sure to read the terms and conditions on the [https://claim.mantarewards.online](https://claim.mantarewards.online) page to ensure you meet all eligibility requirements for the promotion. This offer is for a limited time, so don't miss out!



Winners: @Bertha7179, @agdolla, @klince, @sn0vvdr3am, @oeawFebe, @2268849945, @dedcomfy
